### ISSUE TITLE
Improve the design of cards.

### ISSUE THREAD

**Issue by vyasriday** [vyasriday/css-animations-practice#1]
Improve the design of cards at https://hridayeshsharma.com/css-animations-practice/

**Comment by bhargavgohil25** [comment]
I would like to work on this for hacktoberfest can please assign this it to me?

**Comment by vyasriday** [comment]
Sure @Bhargav252000

**Comment by ion05** [comment]
I would also like to work on this issue. Please assign it to me as well.

**Comment by vyasriday** [comment]
Hey @ion05 I am really sorry buddy, but I don't think it's good idea to assign the same issue to multiple people. You can go through the repo and let me know something else you would want to improve.
